/**
 * The few settings the unit's catalog names or measures wrongly, put right
 * where a block's read lands, so every screen after it says the same thing.
 *
 * "Presence Frequency — 1 Hz." The number was right and the word after it was
 * not: the catalog guesses "hz" for a 0.1 to 10 control that is really kHz, so
 * the knob, the typed box and the search all said 1 Hz about a presence that
 * sits at a thousand. The amp's Tremolo Frequency is tagged dB, and the handful
 * of 0-to-1 settings the amp keeps for its meters are tagged dB as well.
 *
 * KEYED BY BLOCK AND SETTING NUMBER, not by name. The server numbers repeated
 * names ("Frequency 2"), so a name moves when the list does; the number is the
 * setting. Each entry also says what it expects to find — the wrong unit and
 * the range — and leaves alone anything that does not match, so another unit
 * whose setting 28 means something else is never touched, and a catalog that
 * is fixed at the source is simply no longer corrected here.
 *
 * And one name: DYNIMP is Fractal's "Dynamic Damping" (the Axe-Fx II's own
 * label for the same control), which no catalog on this unit carries.
 *
 * Shared, because a phone saying 1 Hz where the browser says 1 kHz is one of
 * them wrong. The phone's copy is generated by `npm run sync:rules`.
 */

/** Settings whose unit is wrong in the catalog: block, setting, what it says, what it is. */
export const UNIT_FIXES = [
  { slug: 'amp', id: 28, from: 'Hz', to: 'kHz', min: 0.1, max: 10 }, // Presence Frequency
  { slug: 'amp', id: 91, from: 'dB', to: 'Hz', min: 0.2, max: 20 }, // Tremolo Frequency
  /* The amp's meters and the one beside them, 0 to 1 and no decibels about them. */
  { slug: 'amp', id: 119, from: 'dB', to: '', min: 0, max: 1 }, // RESOLUTION
  { slug: 'amp', id: 120, from: 'dB', to: '', min: 0, max: 1 }, // B+
  { slug: 'amp', id: 121, from: 'dB', to: '', min: 0, max: 1 }, // Gain (compressor meter)
  { slug: 'amp', id: 122, from: 'dB', to: '', min: 0, max: 1 }, // Gain (speaker meter)
  { slug: 'amp', id: 123, from: 'dB', to: '', min: 0, max: 1 }, // Gain (input dynamics meter)
  { slug: 'amp', id: 132, from: 'dB', to: '', min: 0, max: 1 } // HEADROOM
]

/** Settings the catalog has no name for, and Fractal does. */
export const NAME_FIXES = [{ slug: 'amp', id: 97, from: 'DYNIMP', to: 'Dynamic Damping' }]

const near = (a, b) => typeof a === 'number' && Math.abs(a - b) < 1e-6

function fixOne(slug, p) {
  if (!p || typeof p !== 'object') return p
  let out = p
  const unit = UNIT_FIXES.find((f) => f.slug === slug && f.id === p.id)
  if (unit && p.unit === unit.from && near(p.min, unit.min) && near(p.max, unit.max)) {
    const { unit: _wrong, ...rest } = out
    out = unit.to ? { ...rest, unit: unit.to } : rest
  }
  const name = NAME_FIXES.find((f) => f.slug === slug && f.id === p.id)
  if (name && p.name === name.from) out = { ...out, name: name.to }
  return out
}

/**
 * A block's params read with the known mistakes put right. Anything that is
 * not a read, or a read of a block with nothing to correct, comes back as it
 * came in.
 */
export function fixRead(read) {
  if (!read || typeof read !== 'object' || !Array.isArray(read.named)) return read
  const slug = String(read.slug || '').toLowerCase()
  if (!UNIT_FIXES.some((f) => f.slug === slug) && !NAME_FIXES.some((f) => f.slug === slug)) return read
  return { ...read, named: read.named.map((p) => fixOne(slug, p)) }
}

/**
 * A number and its unit, with a space between: "6.70 dB", "1 kHz", "50 %".
 * Search once ran them together ("1Hz"), where the knob never did.
 */
export const withUnit = (text, unit) => (unit ? `${text} ${unit}` : `${text}`)
