/**
 * WHAT'S LIVE — which version each piece is on, for Justin's Developer page.
 *
 * "Which version each piece is on (iPhone, Android, website, computer app),
 * and whether the latest update has reached phones. Answers 'why am I still
 * on 1.66?' at a glance." (docs/later.md)
 *
 * Everything here is read from public places, so no key goes in the app:
 *
 *   website       /version.json, written into every deploy by vite.config.js
 *   computer app  the latest GitHub release (the desktop apps update from it)
 *   store builds  docs/expo-builds.md, the ledger every Expo build is written in
 *
 * The website deploys from main on every merge, and every merge publishes the
 * same version as an over-the-air update. So the website's version is also
 * the newest update there is, and a phone behind it is a phone the update has
 * not reached yet. That is the "has it reached phones" answer, for the phone
 * in his hand.
 *
 * Shared by the browser and the phone; the phone's copy is generated by
 * `npm run sync:rules`.
 */

export const SITE = 'https://fractal.newbold.cloud'
export const RELEASES = 'https://api.github.com/repos/justinnewbold/fractal-remote/releases/latest'
export const LEDGER = 'https://raw.githubusercontent.com/justinnewbold/fractal-remote/main/docs/expo-builds.md'

/** "1.86.53" from "v1.86.53", "apk-v1.86.53" or "1.86.53"; null otherwise. */
export const versionIn = (text) => (String(text || '').match(/(\d+\.\d+\.\d+)/) || [])[1] || null

/** -1, 0 or 1, comparing two dotted versions number by number. */
export function compareVersions(a, b) {
  const x = String(a || '').split('.').map(Number)
  const y = String(b || '').split('.').map(Number)
  for (let i = 0; i < Math.max(x.length, y.length); i += 1) {
    const d = (x[i] || 0) - (y[i] || 0)
    if (d) return d > 0 ? 1 : -1
  }
  return 0
}

/**
 * The ledger's newest iOS and Android builds, and what is left this month.
 * Rows are "| Date | Version | iOS | Android | What it was for |"; a 1 in a
 * column is a build on that platform.
 */
export function readLedger(text) {
  const out = { ios: null, android: null, left: null }
  for (const line of String(text || '').split('\n')) {
    const cells = line.split('|').map((c) => c.trim())
    if (cells.length < 6 || !versionIn(cells[2])) continue
    if (cells[3] === '1') out.ios = { version: versionIn(cells[2]), date: cells[1] }
    if (cells[4] === '1') out.android = { version: versionIn(cells[2]), date: cells[1] }
  }
  const left = String(text || '').match(/Left this month:\s*([^*\n]+)/g)
  if (left?.length) out.left = left[left.length - 1].replace(/Left this month:\s*/, '').replace(/\.$/, '').trim()
  return out
}

/** Fetch all three, each on its own: one source down must not blank the page. */
export async function fetchLive(fetchImpl = globalThis.fetch) {
  const get = async (url, as) => {
    try {
      const res = await fetchImpl(url, { headers: as === 'json' ? { Accept: 'application/json' } : {}, cache: 'no-store' })
      if (!res.ok) return { failed: `answered ${res.status}` }
      return { value: as === 'json' ? await res.json() : await res.text() }
    } catch (err) {
      return { failed: err?.message || String(err) }
    }
  }
  const [site, release, ledger] = await Promise.all([
    get(`${SITE}/version.json?t=${Date.now()}`, 'json'),
    get(RELEASES, 'json'),
    get(LEDGER, 'text')
  ])
  return { site, release, ledger, at: Date.now() }
}

/**
 * The page's rows. `here` is the end reading it: { kind: 'phone' | 'browser',
 * version, updateWaiting, updatedAt }.
 */
export function liveRows(live, here = {}) {
  const site = live?.site?.value
  const siteVersion = versionIn(site?.version)
  const rel = live?.release?.value
  const computer = versionIn(rel?.tag_name)
  const ledger = live?.ledger?.value ? readLedger(live.ledger.value) : null
  const why = (src) => (src?.failed ? `Couldn't read it (${src.failed})` : 'Not known')

  const rows = [
    {
      label: 'Website',
      value: siteVersion ? `v${siteVersion}${site?.commit ? ` · ${site.commit}` : ''}${site?.built ? `, deployed ${site.built} UTC` : ''}` : why(live?.site)
    },
    { label: 'Newest update', value: siteVersion ? `v${siteVersion}, the same as the website` : why(live?.site) },
    { label: 'Computer app', value: computer ? `v${computer}, the newest release` : why(live?.release) },
    {
      label: 'iPhone build',
      value: ledger?.ios ? `v${ledger.ios.version}, built ${ledger.ios.date}` : why(live?.ledger)
    },
    {
      label: 'Android build',
      value: ledger?.android ? `v${ledger.android.version}, built ${ledger.android.date}` : why(live?.ledger)
    },
    ...(ledger?.left ? [{ label: 'Builds left', value: ledger.left }] : [])
  ]

  if (here.version) {
    const behind = siteVersion && compareVersions(here.version, siteVersion) < 0
    const where = here.kind === 'phone' ? 'This phone' : 'This page'
    let state
    if (!siteVersion) state = ''
    else if (!behind) state = ', up to date'
    else if (here.updateWaiting) state = `, behind v${siteVersion}. The update has downloaded: restart the app to use it.`
    else if (here.kind === 'phone') state = `, behind v${siteVersion}. The update hasn't reached it yet; open and close the app once.`
    else state = `, behind v${siteVersion}. Reload the page.`
    rows.unshift({ label: where, value: `v${here.version}${state}` })
  }
  return rows
}
