/* Generated from shared/mod-read.mjs by scripts/sync-relay-rules.mjs.
 * Do not edit. Change the source and run `npm run sync:rules`; the test suite
 * fails on any difference between the two. */

/**
 * WHAT IS ATTACHED TO EACH MODIFIER — read back off the unit.
 *
 * The Modifiers panel could attach a pedal or an LFO to a control and could
 * not say what was attached already. This reads each modifier slot and says
 * it in a line: "Expression 1 → Drive 1 · Gain".
 *
 * HOW SURE THIS IS. The unit keeps a modifier's binding on the modifier's own
 * block (slot N is block `effectId + N - 1`): the source, the target block and
 * the target control, at the field numbers /mod/model gives. ForgeFX reads a
 * block's stored values back as whole numbers (GET /preset/blocks/:eid/raw),
 * and those are taken here as the numbers the attach wrote. That has not been
 * checked against an FM3 yet. So a line is only drawn when the numbers name a
 * source the unit listed AND a block in this preset — anything else is said
 * as "set up, but the app can't tell what it's attached to", never guessed.
 * Every slot read leaves its raw numbers in the log, so a wrong reading can be
 * found from Copy Logs.
 *
 * Shared by the browser and the phone; the phone's copy is generated by
 * `npm run sync:rules`.
 */

/** The block a modifier slot lives on. Slot is counted from 1. */
export const modSlotEid = (model, slot) => model.effectId + (slot - 1)

/**
 * One slot's stored numbers, taken apart. `values` is the raw read's
 * `{ pid: number }`; the unit leaves zeros out, so an empty read is a slot
 * nobody has set up.
 */
export function slotBinding(values, model) {
  const v = values && typeof values === 'object' ? values : {}
  const used = Object.values(v).some((n) => Number(n) !== 0)
  const f = model?.fields || {}
  const pick = (field) => (f[field] && Number.isInteger(f[field].pid) ? Number(v[f[field].pid] ?? 0) : null)
  return { used, source: pick('source'), target: pick('targetEffectId'), param: pick('targetParam') }
}

/**
 * The line for one slot, or a plain "can't tell". `blocks` is the preset's
 * chain; `controlName(effectId, paramId)` names a control when it can.
 */
export function slotLine(slot, binding, { sources, blocks, controlName }) {
  const src = (sources || []).find((s) => s.ordinal === binding.source)
  const block = (blocks || []).find((b) => b.effectId === binding.target)
  if (!src || binding.source === 0 || !block) {
    return { slot, known: false, text: `Slot ${slot} is set up, but the app can’t tell what it’s attached to yet.` }
  }
  const control = controlName?.(block.effectId, binding.param)
  return {
    slot,
    known: true,
    source: src.name,
    block: block.name,
    control: control || null,
    text: `${src.name} → ${block.name}${control ? ` · ${control}` : ''}`
  }
}

/**
 * Read every slot, one at a time, and say what each one is attached to.
 *
 * `readRaw(eid)` is the raw read; `readControls(eid)` the block's controls
 * (blockParams), read once per block that turns up; `progress({ done, total })`
 * is told as it goes; `stillHere()` false stops it — another preset loaded
 * mid-read is not the preset these slots belong to. `log(line)` gets each
 * slot's raw numbers.
 */
export async function readAttached({ model, blocks, readRaw, readControls, progress, stillHere, log }) {
  const total = Number.isInteger(model?.slotCount) ? model.slotCount : 0
  const lines = []
  let unread = 0
  const controls = new Map()
  const controlName = (eid, pid) => {
    const list = controls.get(eid)
    const p = Array.isArray(list) ? list.find((q) => q?.id === pid) : null
    return p?.name || null
  }
  for (let slot = 1; slot <= total; slot++) {
    if (stillHere && !stillHere()) return { stopped: true, lines, unread, total }
    progress?.({ done: slot - 1, total })
    let values
    try {
      values = (await readRaw(modSlotEid(model, slot)))?.values
    } catch {
      unread += 1
      continue
    }
    if (values === undefined) {
      unread += 1
      continue
    }
    const binding = slotBinding(values, model)
    if (!binding.used) continue
    log?.(`modifier slot ${slot}: ${JSON.stringify(values)}`)
    const block = (blocks || []).find((b) => b.effectId === binding.target)
    if (block && !controls.has(block.effectId) && readControls) {
      const read = await readControls(block.effectId).catch(() => null)
      controls.set(block.effectId, read?.named || [])
    }
    lines.push(slotLine(slot, binding, { sources: model.sources, blocks, controlName }))
  }
  progress?.({ done: total, total })
  return { stopped: false, lines, unread, total }
}

/** The sentence under the list. */
export function attachedSummary(res) {
  if (!res) return null
  if (res.stopped) return 'Stopped — another preset was loaded. Read it again for this one.'
  if (res.unread === res.total && res.total > 0) return 'Couldn’t read the modifier slots from your unit.'
  const missed = res.unread ? ` ${res.unread} slot${res.unread === 1 ? '' : 's'} couldn’t be read.` : ''
  if (!res.lines.length) return `Nothing is attached in this preset.${missed}`
  return missed.trim() || null
}
