/* Generated from shared/watch-link.mjs by scripts/sync-relay-rules.mjs.
 * Do not edit. Change the source and run `npm run sync:rules`; the test suite
 * fails on any difference between the two. */

/**
 * WHAT THE PHONE TELLS THE WATCH, AND WHAT THE WATCH MAY ASK.
 *
 * "Maybe three different screens that you can swipe between … nothing else,
 * just simple actions from the watch." The watch has four pages — the tuner,
 * the scenes, the pedals and the presets — and it does not talk to the
 * computer itself: Apple keeps a watch app off the kind of connection the
 * relay is, so every tap goes watch → phone → computer → unit, over Apple's
 * own watch-to-phone link (WatchConnectivity). The phone is the only thing
 * that knows the rig; the watch draws what it is told and asks for one of
 * four things.
 *
 * This file is both halves of that conversation, in words the watch's Swift
 * can read without knowing anything about the app: `watchState` is what the
 * phone sends (one small document, the whole picture each time, so a watch
 * that missed a message is right again on the next), and `watchCommand` is the
 * only door a message from the watch comes in by. Anything it does not
 * recognise is dropped, never guessed at.
 *
 * The phone's copy is generated by `npm run sync:rules`. The watch's reading
 * of it is mobile/targets/watch/Model.swift; test/run.mjs holds the two to the
 * same field names.
 */

/** Bumped when a field changes meaning, so an old watch can say it is out of date. */
export const WATCH_LINK_VERSION = 1

/** The most pedals a watch page shows. More than this is a phone's job. */
export const WATCH_PEDALS_MAX = 12

/** How often a tuner reading may cross to the watch: about ten a second. */
export const WATCH_TUNER_MS = 100
/** And everything else, at most this often while it is changing. */
export const WATCH_STATE_MS = 250

/** Within this many cents the watch draws the note green, as the phone's tuner does. */
export const WATCH_IN_TUNE_CENTS = 3

const int = (n) => Number.isInteger(n)
const text = (s, max = 40) => (typeof s === 'string' ? s.slice(0, max) : '')

/**
 * The picture the watch draws, from the phone's store and the few things the
 * stage screen works out (the label of the slot, where Previous and Next would
 * land, each pedal's colour and short name).
 *
 * Every field is always present, so the watch never has to wonder whether a
 * missing one means "none" or "unknown".
 */
export function watchState({
  preset = null,
  label = '',
  scene = null,
  sceneNames = [],
  sceneCount = 0,
  pedals = [],
  tunerOn = false,
  tuning = null,
  linked = false,
  canPrevious = false,
  canNext = false,
  at = Date.now()
} = {}) {
  const count = int(sceneCount) && sceneCount > 0 ? Math.min(sceneCount, 8) : 0
  const note = tunerOn && tuning && typeof tuning.note === 'string' && tuning.note ? tuning.note.slice(0, 3) : ''
  const cents = note && Number.isFinite(tuning.cents) ? Math.max(-50, Math.min(50, Math.round(tuning.cents))) : 0
  return {
    v: WATCH_LINK_VERSION,
    at,
    linked: !!linked,
    preset: {
      number: int(preset?.number) ? preset.number : -1,
      label: text(label, 8),
      name: text(preset?.name, 32)
    },
    canPrevious: !!canPrevious,
    canNext: !!canNext,
    scene: int(scene) && scene >= 0 && scene < count ? scene : -1,
    scenes: Array.from({ length: count }, (_, i) => text(sceneNames?.[i], 16) || `Scene ${i + 1}`),
    pedals: (Array.isArray(pedals) ? pedals : [])
      .filter((p) => p && int(p.id))
      .slice(0, WATCH_PEDALS_MAX)
      .map((p) => ({
        id: p.id,
        short: text(p.short, 5) || text(p.name, 5),
        name: text(p.name, 24),
        on: p.on === true,
        fill: /^#[0-9a-f]{6}$/i.test(p.fill || '') ? p.fill : '#7d8591',
        ink: /^#[0-9a-f]{6}$/i.test(p.ink || '') ? p.ink : '#ffffff'
      })),
    tuner: {
      on: !!tunerOn,
      note,
      octave: note && int(tuning?.octave) ? tuning.octave : -1,
      cents,
      inTune: !!note && Math.abs(cents) <= WATCH_IN_TUNE_CENTS
    }
  }
}

/**
 * A message from the watch, as one of the four things it may ask, or null.
 *
 *   { do: 'scene', index }      — switch to that scene (0-based)
 *   { do: 'pedal', id, on }     — that block on or off
 *   { do: 'preset', step }      — Previous (-1) or Next (+1), as the stage screen steps
 *   { do: 'tuner', on }         — the tuner page opened or closed
 *   { do: 'hello' }             — the watch app opened: send the picture now
 *
 * `state` is the last picture sent, so a scene or a pedal the watch could not
 * have been shown is refused rather than sent to the unit.
 */
export function watchCommand(msg, state) {
  if (!msg || typeof msg !== 'object') return null
  switch (msg.do) {
    case 'hello':
      return { do: 'hello' }
    case 'scene': {
      const count = Array.isArray(state?.scenes) ? state.scenes.length : 0
      return int(msg.index) && msg.index >= 0 && msg.index < count ? { do: 'scene', index: msg.index } : null
    }
    case 'pedal': {
      const shown = (state?.pedals || []).some((p) => p.id === msg.id)
      return int(msg.id) && shown && typeof msg.on === 'boolean' ? { do: 'pedal', id: msg.id, on: msg.on } : null
    }
    case 'preset':
      return msg.step === 1 || msg.step === -1 ? { do: 'preset', step: msg.step } : null
    case 'tuner':
      return typeof msg.on === 'boolean' ? { do: 'tuner', on: msg.on } : null
    default:
      return null
  }
}

/**
 * Whether two pictures differ in anything but the clock — so the phone does
 * not wake the watch's radio to say nothing has changed.
 */
export function sameWatchState(a, b) {
  if (!a || !b) return false
  const { at: _a, ...restA } = a
  const { at: _b, ...restB } = b
  return JSON.stringify(restA) === JSON.stringify(restB)
}

/**
 * WHEN TO SEND. The phone's store changes many times a second while somebody
 * plays — a tuner reading every 80 ms, a scene's states landing in two steps —
 * and every send wakes the watch's radio. So a picture goes straight away when
 * nothing has gone for a while, and otherwise once the gap is up: a tenth of a
 * second while only the tuner moved, a quarter for anything else. One that is
 * the same as the last is not sent at all.
 *
 * `send(state, { urgent })` is the native call; urgent is false for a picture
 * that only moved the tuner, so the native side can skip the slower, kept
 * copy (applicationContext) for those. `now`, `schedule` and `cancel` are the
 * clock, injected so the tests can turn it by hand.
 */
export function createWatchSender({ send, now = () => Date.now(), schedule = setTimeout, cancel = clearTimeout }) {
  let last = null
  let lastAt = -Infinity
  let pending = null
  let timer = null

  const tunerOnly = (a, b) => {
    if (!a || !b) return false
    return sameWatchState({ ...a, tuner: null }, { ...b, tuner: null })
  }

  const fire = () => {
    timer = null
    if (!pending) return
    const state = pending
    pending = null
    const urgent = !tunerOnly(last, state)
    last = state
    lastAt = now()
    try {
      send(state, { urgent })
    } catch {
      /* A watch that is not there is not a fault on the phone. */
    }
  }

  return {
    push(state) {
      if (sameWatchState(state, pending || last)) return
      pending = state
      const gap = tunerOnly(last, state) ? WATCH_TUNER_MS : WATCH_STATE_MS
      const wait = Math.max(0, lastAt + gap - now())
      if (wait === 0) {
        if (timer) cancel(timer)
        fire()
      } else if (!timer) {
        timer = schedule(fire, wait)
      }
    },
    /** Send the latest picture now — the watch has just opened and asked. */
    flush(state) {
      if (timer) cancel(timer)
      timer = null
      pending = state || pending || last
      if (pending) {
        last = null
        fire()
      }
    },
    stop() {
      if (timer) cancel(timer)
      timer = null
      pending = null
    }
  }
}
